### ISSUE TITLE
typos in brownie-config.yaml and scripts/aave_borrow.py

### ISSUE THREAD

**Issue by afilcheff** [PatrickAlphaC/aave_brownie_py#1]
While going over the code, both files had 'lending_poll_addresses_provider' which I believe should be 'pool's and could cause potential confusion.

**Comment by PatrickAlphaC** [comment]
addressed in https://github.com/PatrickAlphaC/aave_brownie_py/commit/0061a39fed02123b7fbd64a0e5b29ed62787fb65

Thanks so much!
