### ISSUE TITLE
Tests failing

### ISSUE THREAD

**Issue by DavidWilliamsQA** [PatrickAlphaC/aave_brownie_py#11]
I have run the generic tests added at the end of the tutorial but running into two errors:
1.  TypeError: get_asset_price() missing 1 required positional argument: 'price_feed_address'
2. AssertionError: assert <Transaction '0x8e8f349d64678a12ce68eee1fe48cc3fcd16ef8392513b5d95cd804b9c2946dd'> is True
tests\test_aave_borrow.py:33: AssertionError

**Comment by PatrickAlphaC** [comment]
Try cloning from scratch and running again. I just ran the tests and they worked great over here.

```bash
git clone https://github.com/PatrickAlphaC/aave_brownie_py
cd aave_brownie_py
brownie test
```

Closing for now, feel free to follow up
