### ISSUE TITLE
Is it possible to short sell in kovan testnet and mainnet-fork? If yes where?

### ISSUE THREAD

**Issue by haverstein** [PatrickAlphaC/aave_brownie_py#15]

**Comment by PatrickAlphaC** [comment]
What do you mean where? And yes it's possible to do both.

**Comment by haverstein** [comment]
Where in the sense which platform to short sell? 
But I would take this opportunity to thank you for making this course. It really is helping a lot.

**Comment by PatrickAlphaC** [comment]
So the flow looks like this:

1. Borrow a token (let's say DAI) on Aave
2. Sell the DAI on a dex like uniswap
3. You have officially shorted DAI

that's it. https://www.investopedia.com/terms/s/shortselling.asp
