### ISSUE TITLE
__init__.py in the scripts folder

### ISSUE THREAD

**Issue by jhb10c** [PatrickAlphaC/aave_brownie_py#2]
There is no __init__.py in the scripts folder. This causes the script aave_borrow.py to not find the geth_weth function for python 3.8.8.

**Comment by Shawndon54** [comment]
can you explain more im a begginer.. what should the init.py consist of?

**Comment by PatrickAlphaC** [comment]
How are you running `get_weth.py`? Are you using `python get_weth.py`? 

You should use `brownie run scripts/get_weth.py`

Is that what you're doing?

**Comment by PatrickAlphaC** [comment]
@jhb10c I just tested it on v3.8.8 and it worked for me. Perhaps something else is going on. What version of brownie are you using?

**Comment by PatrickAlphaC** [comment]
Got it worked out with https://github.com/PatrickAlphaC/aave_brownie_py/issues/3. 

https://github.com/PatrickAlphaC/aave_brownie_py/commit/cda67a04ff4b5ce8f79a650ccee275f0d0600428 fixes this. Thank you!

**Comment by jhb10c** [comment]
@PatrickAlphaC  I'm using an older version of brownie: 1.14.6. This was causing the issues. After updating it worked fine! 

@Shawndon54 '__init__.py' is an empty file that tells python to use these files as a package.  Here is a more in depth [explaination](https://stackoverflow.com/questions/448271/what-is-init-py-for).
