### ISSUE TITLE
calling get_weth function problem in aave_borrow.py file

### ISSUE THREAD

**Issue by veridelisi** [PatrickAlphaC/aave_brownie_py#3]
I got error when execute aave_borrow.py . I got error in the following line 
"from scripts.get_weth import get_weth"

error 
**No module named scripts. get_weth**

I solve this as follows:
I deleted line 3 in aave_borrow.py
and I paste this

def get_weth(account=None):
    """
    Mints WETH by depositing ETH.
    """
    account = (
        account if account else accounts.add(config["wallets"]["from_key"])
    )  # add your keystore ID as an argument to this call
    weth = interface.WethInterface(
        config["networks"][network.show_active()]["weth_token"]
    )

**Comment by PatrickAlphaC** [comment]
What is the command you're using to run the script?

**Comment by veridelisi** [comment]
brownie run scripts/aave_borrow.py --network kovan
or
brownie run scripts/aave_borrow.py --network mainnet-fork

**Comment by PatrickAlphaC** [comment]
hmm... I'm not able to reproduce this error.

Can you run `python --version`? And also what OS are you working on?

**Comment by veridelisi** [comment]
Python 3.8.8
NAME="Ubuntu"
VERSION="20.04.2 LTS

**Comment by PatrickAlphaC** [comment]
What version of brownie? I just tested on v 3.8.8 of python, ubuntu, 20.04.2 LTS and it still worked for me

Wondering what else might be going on. I don't think you should have to have a `__init__.py` in there.

**Comment by veridelisi** [comment]
Brownie v1.14.6

**Comment by PatrickAlphaC** [comment]
What happens when you put a `__init__.py` file in `scripts`? Does it work then?

**Comment by veridelisi** [comment]
it is working now ! Thank you sir!

**Comment by PatrickAlphaC** [comment]
Oh wow that did work huh. I guess I'll update this.

Thanks for making this issue!
