### ISSUE TITLE
Our wallet being minted some "Aave Stable Debt Bearing DAI"

### ISSUE THREAD

**Issue by veridelisi** [PatrickAlphaC/aave_brownie_py#4]
Hello Patrick
could you clarify this statement?
what is happened in second transaction, layman terms, please?
in the third transaction, this Aave Stable Debt Bearing DAI turns to DAI?

![patrick1](https://user-images.githubusercontent.com/72710290/123318372-cd58d280-d537-11eb-8b70-50561a42b4ea.png)

**Comment by PatrickAlphaC** [comment]
Yes! When you borrow an asset, you have to pay that asset back at some point.

The stable bearing debt is the debt you owe back to the platform.
