### ISSUE TITLE
total_debt_eth, available_borrow_eth and available_borrow_eth

### ISSUE THREAD

**Issue by veridelisi** [PatrickAlphaC/aave_brownie_py#5]
patrickhello

where are the calculated these 3 variables?   

print(f"You have {total_debt_eth} worth of ETH borrowed.")
print(f"You can borrow {available_borrow_eth} worth of ETH.")
print(f"You can borrow {available_borrow_eth} worth of ETH.")

![a13](https://user-images.githubusercontent.com/72710290/123318697-2c1e4c00-d538-11eb-81e0-46c078b13ed5.png)

**Comment by PatrickAlphaC** [comment]
`total_debt_eth` - This is the total debt you have in terms of ETH
`available_borrow_eth` - This is how much you can borrow based on the amount of collateral you've put down in terms of ETH
`available_borrow_eth` - This is the same thing... perhaps you mean `total_collateral_eth`, which is how much you have deposited.

**Comment by veridelisi** [comment]
Patrick hello
How do you calculate **available_borrow_eth** and **total_debt_eth** ?
do you connect lending pool?

available_borrow_eth = Web3.fromWei(available_borrow_eth, "ether")
 total_collateral_eth = Web3.fromWei(total_collateral_eth, "ether")
