### ISSUE TITLE
missing withdraw function

### ISSUE THREAD

**Issue by AlbertoSinigaglia** [PatrickAlphaC/aave_brownie_py#8]
this contract 

https://github.com/PatrickAlphaC/aave_brownie_py/blob/cda67a04ff4b5ce8f79a650ccee275f0d0600428/interfaces/WethInterface.sol#L2-L10

is missing:
```solidity
function withdraw(uint wad) public;
```

**Comment by PatrickAlphaC** [comment]
Thanks. You can actually use interfaces even without all the functions, and we don't use the `withdraw` functionality in this project. 

If you'd like to add the function, could you make a PR?

**Comment by PatrickAlphaC** [comment]
Closing since not needed, but feel free to make a PR to add!

**Comment by PatrickAlphaC** [comment]
On second thought, I see the rest of where this request is coming from. Added in 7519e902e82668bf35a84ddfc40984ad6399d7da
