### ISSUE TITLE
Decimal support to get_asset_price

### ISSUE THREAD

**Issue by altugbakan** [PatrickAlphaC/aave_brownie_py#9]
Hey Patrick! Thanks for the course!

In the current state of our aave_borrow script, we are converting the price feed "from Wei". We saw that the decimals for the Chainlink price feeds might change; so, can't we use the decimals() function of the price feed smart contract to make our code more general?

I also added a pull request for this issue [here](https://github.com/PatrickAlphaC/aave_brownie_py/pull/10)!

**Comment by PatrickAlphaC** [comment]
Thank you! I commented on the PR
